name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for product-service
        working-directory: ./product-service
        run: npm install

      - name: Install dependencies for customer-service
        working-directory: ./customer-service
        run: npm install

      - name: Run tests for product-service
        working-directory: ./product-service
        run: npm test

      - name: Run tests for customer-service
        working-directory: ./customer-service
        run: npm test

      - name: Dockerize product-service
        working-directory: ./product-service
        run: docker build -t product-service:latest .

      - name: Dockerize customer-service
        working-directory: ./customer-service
        run: docker build -t customer-service:latest .

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Tag and Push Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker tag product-service:latest "$DOCKER_USERNAME"/product-service:latest
          docker push "$DOCKER_USERNAME"/product-service:latest
          docker tag customer-service:latest "$DOCKER_USERNAME"/customer-service:latest
          docker push "$DOCKER_USERNAME"/customer-service:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose pull
          docker-compose up -d
