name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd product-service
          npm install
          cd ../customer-service
          npm install

      - name: Run tests (optional)
        run: |
          cd product-service
          # Add tests here, e.g., run a simple test command
          cd ../customer-service
          # Add tests here, e.g., run a simple test command

      - name: Dockerize the services (optional for production)
        run: |
          cd product-service
          docker build -t product-service .
          cd ../customer-service
          docker build -t customer-service .

      - name: Push Docker images (optional)
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push product-service
          docker push customer-service
